# Generated by Django 5.0.4 on 2024-05-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassList',
            new_name='CarList',
        ),
    ]
