# Generated by Django 5.0.4 on 2024-05-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carlist_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Showrooms', to='app.showroomlist'),
        ),
    ]
